### ISSUE TITLE
Serial_read.c

### ISSUE THREAD

**Issue by tfdahlin** [Sam-son/Ev3-CPP#1]
Alright, so in an attempt to compile what should be working code for reading from the serial ports, I realized that the code looks a lot like the outdated stuff that was initially sent out last year. I know that, later on in the class, you sent out updated files (namely, serial_read.cpp, serial_read.h, and defines.h), and I have confirmed that these do not match the ones currently included with what the students have. In addition, looking at the source for your build script, it does not appear that serial_read.c is included in the process of the build.

**Comment by X-sam** [comment]
Resolved as of 4f24703
